document.getElementById("btnExames").onclick = function() {
  window.location.href = "../Paciente/ResultadoExames/Resultado.html";
};

document.getElementById("btnAtestados").onclick = function () {
  window.location.href = "../Paciente/Atestados/Atestado.html";
};

document.getElementById("btnMinhasConsultas").onclick = function () {
  window.location.href = "../Paciente/MinhasConsultas/MinhasConsultas.html";
};

document.getElementById("btnAgendarConsultas").onclick = function () {
  window.location.href = "../Paciente/AgendarConsultas/AgendarConsultas.html";
};
